name: Continous Integration

on: [pull_request, push]

jobs:
  ci-job:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 3
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9, pypy3 ]
    name: CI job (python ${{ matrix.python-version }})

    services:
      postgres:
        image: postgres:12.0-alpine
        env:
          POSTGRES_USER: wger
          POSTGRES_PASSWORD: wger
          POSTGRES_DB: wger
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a health check
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5


    steps:
      - uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel coverage
          pip install -r requirements_prod.txt
          python setup.py develop

      # Only run the tests with coverage for one version of python
      - name: Test the application with coverage (Postgres)
        run: |
          wger create-settings --database-type postgresql
          coverage run --source='.' ./manage.py test
          coverage html --directory coverage-postgres
          coverage report
        if: matrix.python-version == 3.8

      - name: Test the application (Postgres)
        run: |
          wger create-settings --database-type postgresql
          python manage.py test
        if: matrix.python-version != 3.8

      # - name: Test the application (Sqlite)
      #  run: |
      #    wger create-settings
      #    coverage run --source='.' ./manage.py test
      #    coverage html --directory coverage-sqlite
      #    coverage report

      - name: Save coverage result artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage-results-${{ matrix.python-version }}
          path: coverage-postgres/
        if: matrix.python-version == 3.8
